version: '3'

services:
  # Nginx流媒体服务器
  nginx:
    image: nginx:alpine
    ports:
      - "8081:80"
      - "8443:443"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - ./data/cache:/var/cache/nginx
      - ./data/logs/nginx:/var/log/nginx
      - ./data/streams:/var/cache/streams
      - ./data/ssl:/etc/nginx/ssl
    restart: always
    depends_on:
      - stream-service
    networks:
      - ytb-stream-network

  # YouTube流处理服务
  stream-service:
    build:
      context: ./stream-service
      dockerfile: Dockerfile
    environment:
      - YOUTUBE_API_KEY=${YOUTUBE_API_KEY}
      - MAX_QUALITY=true
      - BUFFER_SIZE=120
      - TOKEN_SECRET=${TOKEN_SECRET}
    volumes:
      - ./data/streams:/app/streams
      - ./data/logs/stream-service:/app/logs
    restart: always
    networks:
      - ytb-stream-network

  # 监控服务
  monitor:
    build:
      context: ./monitor
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data/logs:/app/logs
      - ./data/streams:/app/streams:ro
    depends_on:
      - nginx
      - stream-service
    restart: always
    networks:
      - ytb-stream-network

networks:
  ytb-stream-network:
    driver: bridge
